# Data cleaning in Python with pandas

##  Setup

With this Google Colaboratory (Colab) notebook open, click the "Copy to Drive" button that appears in the menu bar. The notebook will then be attached to your own Google user account, so you can edit it in any way you like -- you can even take notes directly in the notebook.

## Agenda

1. **Guided instruction**: An instructor will work through the guided activity and teach concepts along the way.

2. **Collaborative exercises**: After the guided portion of the workshop, we will have time to work collaboratively on provided exercises, ask questions, and discuss any concepts relevant to the materials. (Exercises can also be completed outside of the meeting time. A link to the filled version of this notebook containing all of the completed code is available at the end of the notebook under the section *Further resources* for reference)

## Learning objectives

By the end of our workshop today, we hope you'll understand what the pandas library is and be able to use pandas to load, explore, and manipulate data.

### Today's Topics

- Reading and writing data files

- Exploring dataset characteristics

- Manipulating a dataset (adding/removing/editing data)

- Filtering a dataset

### Using Jupyter Notebooks and Google Colaboratory

Jupyter notebooks are a way to write and run Python code in an interactive way. They're quickly becoming a standard way of putting together data, code, and written explanations or visualizations into a single document and sharing that. There are a lot of ways that you can run Jupyter notebooks, including just locally on your computer, but we've decided to use Google's Colaboratory notebook platform for this workshop.  Colaboratory is “a Google research project created to help disseminate machine learning education and research.”  If you would like to know more about Colaboratory in general, you can visit the [Welcome Notebook](https://colab.research.google.com/notebooks/welcome.ipynb).

Using the Google Colaboratory platform allows us to focus on learning and writing Python in the workshop rather than on setting up Python, which can sometimes take a bit of extra work depending on platforms, operating systems, and other installed applications. If you'd like to install a Python distribution locally, though, we're happy to help. Feel free to [get help from our graduate consultants](https://www.lib.ncsu.edu/dxl) or [schedule an appointment with Libraries staff](https://go.ncsu.edu/dvs-request).

## Guided Instruction

**Content Warning:** This dataset contains information relating to violence towards animals. We understand that this may be distressing, and if you need to step away from the workshop we understand.

In this section, we will work through examples using data from the [Federal Aviation Administration (FAA) Wildlife Strikes Database](https://wildlife.faa.gov/search). We have filtered the data to only include North Carolina.

> "The FAA Wildlife Strike Database contains records of reported wildlife strikes since 1990. Strike reporting is voluntary. Therefore, this database only represents the information we have received from airlines, airports, pilots, and other sources." - [FAA website](https://wildlife.faa.gov/home)

### Import the data and the pandas library

To start, we must first load the pandas library into our Python environment and load in our datasets

#### Import pandas

Pandas is a high-level data manipulation tool first created in 2008 by Wes McKinney. The name comes from the term “panel data,” an econometrics term for data sets that include observations over multiple time periods for the same individuals.<sup>[[wikipedia](https://en.wikipedia.org/wiki/Pandas_(software))]</sup>

From Jake Vanderplas’ book [*Python Data Science Handbook*](http://shop.oreilly.com/product/0636920034919.do):

> As well as offering a convenient storage interface for labeled data, Pandas implements a number of powerful data operations familiar to users of both database frameworks and spreadsheet programs.

#### What does Pandas do?

- Reading and writing data from persistent storage

- Cleaning, filtering, and otherwise preparing data

- Calculating statistics and analyzing data

- Visualization with help from the Matplotlib plotting library

In [4]:
# Import the Pandas library as pd (callable in our code as pd)
import pandas as pd

#### Import datasets

We have prepared the data from the FAA website for this workshop. We will import those datasets into our notebook to use them for this activity.

- [Preview the CSV file (opens on GitHub)](https://github.com/NCSU-Libraries/data-viz-workshops/blob/master/Python_Open_Labs/data/FAA_Wildlife_strikes_1990-1999.csv) - wildlife strike data from the years 1990-1999
-[Preview the Excel file (this link will download the file)](https://github.com/NCSU-Libraries/data-viz-workshops/blob/master/Python_Open_Labs/data/FAA_Wildlife_strikes_2000-2009.xlsx?raw=true) - wildlife strike data from the years 2000-2009
- [Preview the JSON file (opens on GitHub)](https://raw.githubusercontent.com/NCSU-Libraries/data-viz-workshops/master/Python_Open_Labs/data/FAA_Wildlife_strikes_2010-2019.json) - wildlife strike data from the years 2010-2019

In [5]:
# Import the CSV file (wildlife strike data from the years 1990-1999)
csv_file_url = 'https://raw.githubusercontent.com/ncsu-libraries-data-vis/data-cleaning-in-python-with-pandas/main/data/FAA_Wildlife_strikes_1990-1999.csv'
data90 = pd.read_csv(csv_file_url)

# Print out the first five columns of the dataset
data90.iloc[:,:5]

     INDX_NR INCIDENT_DATE   INCIDENT_MONTH  INCIDENT_YEAR   TIME
0     633309     1999-12-24              12           1999  10:15
1     634726     1999-12-15              12           1999
2     636216     1999-12-14              12           1999  07:40
3     633739     1999-12-11              12           1999  17:00
4     636671     1999-12-11              12           1999
..       ...            ...             ...            ...    ...
664   611224     1990-06-01               6           1990
665   609163     1990-05-04               5           1990  11:35
666   611004     1990-04-20               4           1990
667   828185     1990-03-21               3           1990  21:30
668   608234     1985-01-06               1           1985

[669 rows x 5 columns]

In [6]:
# Import the Excel file (wildlife strike data from the years 2000-2009)
xls_file_url = 'https://github.com/ncsu-libraries-data-vis/data-cleaning-in-python-with-pandas/blob/main/data/FAA_Wildlife_strikes_2000-2009.xlsx?raw=true'

data00 = pd.read_excel(xls_file_url)
# Print out the first five columns of the dataset
data00.iloc[:,:5]

     INDX_NR INCIDENT_DATE   INCIDENT_MONTH  INCIDENT_YEAR   TIME
0     707074     2009-12-24              12           2009  07:52
1     707361     2009-12-13              12           2009
2     707050     2009-12-11              12           2009  07:26
3     707146     2009-12-10              12           2009  16:45
4     707624     2009-12-08              12           2009  07:30
..       ...            ...             ...            ...    ...
956   642246     2000-02-21               2           2000
957   643020     2000-02-05               2           2000  07:05
958   646738     2000-01-14               1           2000
959   639146     2000-01-10               1           2000
960   639430     2000-01-04               1           2000

[961 rows x 5 columns]

In [7]:
#Import the JSON file (wildlife strike data from the years 2010-2019)
json_file_url = 'https://raw.githubusercontent.com/ncsu-libraries-data-vis/data-cleaning-in-python-with-pandas/main/data/FAA_Wildlife_strikes_2010-2019.json'

data10 = pd.read_json(json_file_url)
# Print out the first five columns of the dataset
data10.iloc[:,:5]

        INCIDENT_DATE   INCIDENT_MONTH  INCIDENT_YEAR   TIME TIME_OF_DAY
1080125     2020-11-05              11           2020  05:00        None
1080118     2020-11-05              11           2020  22:35        None
1080126     2020-11-05              11           2020  11:00         Day
1080130     2020-11-05              11           2020  06:52         Day
1078243     2020-11-04              11           2020  05:20        Dawn
...                ...             ...            ...    ...         ...
709088      2010-01-18               1           2010  10:12         Day
709085      2010-01-17               1           2010  10:40         Day
710034      2010-01-17               1           2010  14:42         Day
709048      2010-01-11               1           2010                Day
710700      2010-01-01               1           2010  17:11         Day

[3334 rows x 5 columns]

### Explore the data

Now that we have our data, we can use pandas to explore it. This can be useful if you are new to a dataset and want to understand what it contains.

#### Pandas data structures

Pandas uses two main data structures: `Series` and `DataFrame`. **The data we imported is structured as a `DataFrame`.**

<img src="https://raw.githubusercontent.com/NCSU-Libraries/data-viz-workshops/master/Data_Manipulation_with_Python/assets/nc_dataframes.png" alt="DataFrames are composed of Series" width="60%">

A `Series` is a one-dimensional array of indexed data, or a single column of data with labels. You can learn more about the Series data type in the [Pandas documentation for Series](https://pandas.pydata.org/pandas-docs/stable/reference/series.html).

A `DataFrame` is a two-dimensional array composed of two or more `Series`, similar to tabluar data (think of Excel). They have row labels (an `Index`) and column labels. You can learn more about the DataFrame data type in the [Pandas documentation for DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html).

A `DataFrame` is made up of `Series` in a similar way in which a table is made up of columns. The only restriction is that each column must be of the same data type. Many of the operations that can be performed on a `DataFrame` can also be performed on an individual `Series`.

#### Referencing and indexing a DataFrame

The pandas library provides utilities to easily reference specific columns and rows from our DataFrame.

##### Referencing columns

In [8]:
# View column labels (headers)
data90.columns

Index(['INDX_NR', 'INCIDENT_DATE ', 'INCIDENT_MONTH', 'INCIDENT_YEAR', 'TIME',
       'TIME_OF_DAY', 'AIRPORT_ID', 'AIRPORT', 'RUNWAY', 'STATE', 'FAAREGION',
       'LOCATION', 'ENROUTE STATE', 'OPID', 'REG', 'FLT', 'AIRCRAFT', 'AMA',
       'AMO', 'EMA', 'EMO', 'AC_CLASS', 'AC_MASS', 'TYPE_ENG', 'NUM_ENGS',
       'ENG_1_POS', 'ENG_2_POS', 'ENG_3_POS', 'ENG_4_POS', 'PHASE_OF_FLIGHT',
       'HEIGHT', 'SPEED', 'DISTANCE', 'SKY', 'PRECIPITATION', 'AOS',
       'COST_REPAIRS', 'OTHER_COST', 'COST_REPAIRS_INFL_ADJ',
       'COST_OTHER_INFL_ADJ', 'INGESTED', 'INDICATED_DAMAGE', 'DAMAGE_LEVEL',
       'STR_RAD', 'DAM_RAD', 'STR_WINDSHLD', 'DAM_WINDSHLD', 'STR_NOSE',
       'DAM_NOSE', 'STR_ENG1', 'DAM_ENG1', 'STR_ENG2', 'DAM_ENG2', 'STR_ENG3',
       'DAM_ENG3', 'STR_ENG4', 'DAM_ENG4', 'STR_PROP', 'DAM_PROP',
       'STR_WING_ROT', 'DAM_WING_ROT', 'STR_FUSE', 'DAM_FUSE', 'STR_LG',
       'DAM_LG', 'STR_TAIL', 'DAM_TAIL', 'STR_LGHTS', 'DAM_LGHTS', 'STR_OTHER',
       'DAM_OTHER', 'OTHER_SPECIFY', 'EFFECT', 'EFFECT_OTHER', 'SPECIES_ID',
       'REMARKS', 'REMAINS_COLLECTED', 'REMAINS_SENT', 'WARNED', 'BIRDS_SEEN',
       'BIRDS_STRUCK', 'SIZE', 'NR_INJURIES', 'NR_FATALITIES', 'COMMENT',
       'REPORTER_NAME', 'REPORTER_TITLE', 'SOURCE', 'PERSON', 'LUPDATE',
       'TRANSFER'],
      dtype='object')

In [12]:
# Reference a column from a DataFrame
data90["SOURCE"]

                   SOURCE                    PERSON
0         FAA Form 5200-7  Air Transport Operations
1         FAA Form 5200-7                       NaN
2         FAA Form 5200-7                     Tower
3         FAA Form 5200-7                     Tower
4    Air Transport Report  Air Transport Operations
..                    ...                       ...
664       FAA Form 5200-7                       NaN
665       FAA Form 5200-7                     Tower
666       FAA Form 5200-7                       NaN
667                  BASH                       NaN
668                  NTSB                     Other

[669 rows x 2 columns]

In [13]:
# Reference multiple columns from a DataFrame
data90[["SOURCE","PERSON"]]

                   SOURCE                    PERSON
0         FAA Form 5200-7  Air Transport Operations
1         FAA Form 5200-7                       NaN
2         FAA Form 5200-7                     Tower
3         FAA Form 5200-7                     Tower
4    Air Transport Report  Air Transport Operations
..                    ...                       ...
664       FAA Form 5200-7                       NaN
665       FAA Form 5200-7                     Tower
666       FAA Form 5200-7                       NaN
667                  BASH                       NaN
668                  NTSB                     Other

[669 rows x 2 columns]

##### Referencing rows

In [15]:
# View the row index labels from a DataFrame
data90.index

RangeIndex(start=0, stop=669, step=1)

In [18]:
# Reference a row by index label using .loc

# Access first row of wl_strikes_csv by index label
# In this case the index label is 0
data90.loc[0]

# Access first row of wl_strikes_json by index label
# In this case the index label is not 0
data10.loc[1080125]

INCIDENT_DATE             2020-11-05
INCIDENT_MONTH                    11
INCIDENT_YEAR                   2020
TIME                           05:00
TIME_OF_DAY                     None
                         ...
REPORTER_TITLE              REDACTED
SOURCE             FAA Form 5200-7-E
PERSON            Airport Operations
LUPDATE                   2020-12-04
TRANSFER                       False
Name: 1080125, Length: 90, dtype: object

In [ ]:
# Reference multiple rows by index label (in this case the index label 0 through 2)
# Returns a DataFrame

In [ ]:
# Reference a row or multiple rows by zero-based integer position

# Access first row of wl_strikes_csv by row integer value
# In this case the row is row 0
data90.iloc[0]

# Access first row of wl_strikes_json by row integer value
# In this case the row is also row 0
data10.iloc[0]

In [ ]:
# Reference multiple rows by row number (in this case rows 0 through 2)
# Note that this time the range doesn't include the stop number

##### Referenceing both rows and columns

In [ ]:
# Referencing a subset of rows and columns using index and column labels
# Note that we're using a range of column labels instead of a list
# Make sure that your column range starts with the leftmost label

#### View summaries of a DataFrame

We can quickly generate summaries of our DataFrame to observe some basic statistics and information such as column data types and non-null value counts.

In [ ]:
# Get the "shape" of the Dataframe (the number of rows and columns)

In [ ]:
# Get summary statistics of DataFrame columns using "describe()" (only includes
# numerical data types)

In [ ]:
# Get summary statistics of single column using "describe()"

In [ ]:
# Summarize column data types, non-null values, and memory usage using "info()"

### Manipulate the data

After exploring our data, we can use pandas to add, remove, and change data to create a dataset or multiple datasets that are more suited for our analyses.

#### Reset DataFrame index labels
The JSON file we imported does not include the column `INDX_NR`. Instead, these values are used as the index labels. We want this dataset to match the format of our other datasets, so we first need to reset the index using the DataFrame method `reset_index()`.

In [ ]:
# Print out the first five rows of the JSON DataFrame


# Reset the JSON DataFrame index


# Print out the first five rows of the dataset

#### Rename column labels

When we reset our index a new column `index` was created. Let's change the name of this column to `INDX_NR` to match our other datasets using the DataFrame `rename()` method.

In [ ]:
# Rename the column we created


# Print out the first five rows of the dataset

#### Concatenate the three DataFrames

We want to be able to work with all of the data we have imported at once, so we need to pull all three DataFrames into one. They all have the same columns now, so we can concatenate them based on columns (similar to adding them together, one on top of another) using the pandas method `concat()`. We also need to consider the current index labels for each dataset. We will create a new zero-based integer index label for the concatenated dataset by passing the keyword argument `ignore_index=True` into the `concat()` method.

In [ ]:
# Concatenate all the datasets into one


# Print the shape (number of rows and columns) of the full DataFrame

#### Merge DataFrames

Our dataset includes a column of species IDs (`SPECIES_ID`) that consist of alpha-numeric codes that reference a specific species of animal. This code is not very helpful if we want to know the species name of an animal involved in a strike. Let's join our dataset with another dataset containing unique species IDs and species names using the shared column `SPECIES_ID` to generate a new column of data (`SPECIES`) containing species name using `merge()`. The URL to the dataset of species IDs and names is stored in the variable `species_names_file_url`.

In [ ]:
# Load the species ID table (stored in a CSV file)
species_names_file_url = 'https://raw.githubusercontent.com/ncsu-libraries-data-vis/data-cleaning-in-python-with-pandas/main/data/FAA_Wildlife_species_id_table.csv'


# Print the loaded species ID table

![Left join visual example](https://github.com/NCSU-Libraries/data-viz-workshops/blob/master/Python_Open_Labs/Data_wrangling_with_Pandas/left-join.png?raw=true)

In [ ]:
# Create a new DataFrame from a "left" join of the full dataset and the species
# ID table based on the shared column "SPECIES_ID"


# Print out the columns "SPECIES" and "SPECIES_ID" from the new merged dataset

#### Removing unnecessary columns

We can reduce the size of our dataset by removing unnecessary columns of data using the DataFrame `drop()` method.

In [ ]:
# Remove the "STATE", "FAAREGION", and "COMMENT" columns using "drop()""


# Print out the shape of the new DataFrame (should only contain 89 columns)

#### Calculating new columns

We can add new data to our dataset by manipulating existing data.

##### Create a new column using an expression

We may want to add a new column that is calculated based on other columns. In this example, we create a new column (`SINGLE_OR_MULTI_ENGINE`) of boolean values that tells us if the plane was a single-engine (TRUE) or a multi-engine (FALSE) plane using a comparison operator to test if the value in the column `NUM_ENGS` equals 1.

In [ ]:
# Print out the "NUM_ENGS" column


# Create a new column of boolean values indicating single- or multi-engine


# Print out the new column

##### Create a new column using `apply()`

Sometimes you need to create a new column based on more complex manipulation of existing data. In this example, we use the `apply()` method to apply the function `calc_hour` along the rows in the column `TIME`. The `calc_hour` function parses an integer value of the hour from a string containing the time at which a strike occurred. We create a new column `HOUR` that contains a numerical representation of the hour in which a strike occurred.

In [ ]:
# Define a function that takes a time string in the form "HH:MM" and returns the
# hour as an integer if the hour value is valid
def calc_hour(time_str):
    # Split the string on the occurance of ":" and take the first value
    hour = time_str.split(':')[0]
    # If the string is not empty return the strint cast as an integer
    if hour.strip(' ') != '':
        return int(hour)

# Print out the "TIME" column


# Use the DataFrame apply() method to call calc_hour on the "TIME" column and
# create a new column "HOUR" in our DataFrame


# Print out the "TIME" and "HOUR" columns from our DataFrame

#### Replace values in a column

We can replace values in a column based on conditions, similar to "find and replace." In this example, we make our new `SINGLE_OR_MULTI_ENGINE` column more descriptive by changing `True` into " Single engine" and `False` into "Multi engine".

In [ ]:
# Replace True or False values with new strings, "Single engine" or "Multi engine"


# Print out the updated column of data

#### Filtering

We can filter our data using conditional statements. This can help us remove unecessary rows of data or observe a specific range of data.

In [ ]:
# Print out unique values from column "TIME_OF_DAY"


# Filter the data to only see incidents that happened at night


# Print out the filtered data

In [ ]:
# Filter the data using "INCIDENT_YEAR" to only see data from 2010 and after


# Print out the filtered data

In [ ]:
# Filter the data to only see incidents from 2010 and after that happened at
# night using the columns "TIME_OF_DAY" and "INCIDENT_YEAR"


# Print out the filtered data

### Write data to a file

After completing our manipulation, we may want to save our final dataset for future analyses.

In [ ]:
# Write to csv

## Collaborative exercises

We can use this time to work on the following exercises or ask questions.

### Exercise 1: Indexing cells

Use referencing and indexing to answer the following questions by finding the data in the rows, columns, and/or cells.

#### 1a. Time of day
Airlines are interested in when they should schedule flights to minimize collisions. What is the time of day for each incident? Create a `Series` of the time of day (`TIME_OF_DAY`)

In [ ]:
# Create a `Series` of the time of day (`TIME_OF_DAY`)


# Print new Series

#### 1b. Date and time
We want to find out when most of these collisions occur. What is the exact date and time of each incident? Print the third, fourth, and fifth columns from the data (`INCIDENT_MONTH`,	`INCIDENT_YEAR`, and	`TIME`).

In [ ]:
# Print the third, fourth, and fifth columns from the data
# (`INCIDENT_MONTH`, `INCIDENT_YEAR`, and `TIME`).

#### 1c. Access the 126th row

Use row indexing to find the data in the 126th row in the `wl_strikes_json` DataFrame. Check that your result is correct by making sure your `INCIDENT_DATE` value is `2020-07-17`.

> Tip: Remember that the integer-based row location is zero based

In [ ]:
# Access the 126th row from the 'wl_strikes_json` DataFrame

#### 1d. Cloud cover
A particular airline has nine flights that they want to compare to see if the cloud cover in the area had anything to do with the collision. Print rows 60-65 and the columns `INDX_NR`, `SKY`, `PHASE_OF_FLIGHT`, and `AIRPORT`

In [ ]:
# 2Print rows 60-65 and the columns 'INDX_NR', 'SKY', 'PHASE_OF_FLIGHT', and
# 'AIRPORT'

### Exercise 2: Rename column headers

Rename the column `REG` to the more descriptive `AIRCRAFT_REGISTRATION`

In [ ]:
# Change the column name "REG" to "AIRCRAFT_REGISTRATION"


# Print out the new DataFrame columns

### Exercise 3: Remove unnecessary columns

The are several columns of data that are not relevant for our analyses. Remove all columns related to engine and damage location (e.g., all the columns that begin with `ENG_`, `DAM_`, and `STR_`). A list of these column names is provided in the variable `drop_columns`.

**Bonus:** See if you can derive the column names in the list `drop_columns` from the dataset

In [ ]:
# A list of column names to remove from the DataFrame
drop_columns = ['ENG_1_POS', 'ENG_2_POS', 'ENG_3_POS', 'ENG_4_POS', 'STR_RAD',
                'DAM_RAD', 'STR_WINDSHLD', 'DAM_WINDSHLD', 'STR_NOSE',
                'DAM_NOSE', 'STR_ENG1', 'DAM_ENG1', 'STR_ENG2', 'DAM_ENG2',
                'STR_ENG3', 'DAM_ENG3', 'STR_ENG4', 'DAM_ENG4', 'STR_PROP',
                'DAM_PROP', 'STR_WING_ROT', 'DAM_WING_ROT', 'STR_FUSE',
                'DAM_FUSE', 'STR_LG', 'DAM_LG', 'STR_TAIL', 'DAM_TAIL',
                'STR_LGHTS', 'DAM_LGHTS', 'STR_OTHER', 'DAM_OTHER']

# Remove unnecessary columns


# Print out the new DataFrame columns

### Exercise 4: Filter out unnecessary rows

Our dataset should only contain data from the years 1990-2019. Remove any rows of data that contain strikes that occurred outside of this year range.

In [ ]:
# Filter out rows of data that contain strikes that occurred outside of the year
# range 1990-2019


# Print out the new filtered DataFrame

### Exercise 5: Join airline operator names with the full dataset

Our dataset contains a column of airline operator IDs (`OPID`). These IDs correspond with airline operator names (e.g., Delta Airlines, Military, United Airlines, etc.). We have another dataset that contains arline operator IDs (in a column named `OPID`) and the corresponding airline operator name (in a column named `OPERATOR`). The URL to this dataset is stored in the variable `op_name_file_url`. Load this dataset and use a left join to merge the operator name with the full dataset.

In [ ]:
# URL to the CSV file containing unique airline operator IDs and names
op_name_file_url = 'https://github.com/NCSU-Libraries/data-viz-workshops/blob/master/Python_Open_Labs/data/FAA_Wildlife_operator_id_table.csv?raw=true'

# Load the operator ID and name dataset into a DataFrame


# Join airline operator names to the full dataset using matching operater IDs


# Print out the columns "OPID" and "OPERATOR" from the new merged DataFrame

### Exercise 6: Create a new column containing month names

Our dataset currently contains a column of integer values representing the month number in which a strike occurred (1-12). It would be helpful to have a column containing the month name (e.g., January, February, etc.). Calculate a new column labeled `MONTH_NAME` containing the month name in which a stike occurred.

**TIP:** There are multiple ways you could consider creating this new column (e.g., using `replace()` or `apply()`), but it might be helpful to have a way to map month numbers (1-12) to month names (January - December) (e.g., a list or dictionary).

In [ ]:
# Create a new column "MONTH_NAME" containing month names in which a strike occurred

## Further resources

### Filled version of this notebook

[Data Cleaning in Python with pandas filled notebook](https://colab.research.google.com/github/ncsu-libraries-data-vis/data-cleaning-in-python-with-pandas/blob/main/Data_Cleaning_in_Python_with_pandas_filled.ipynb) - a version of this notebook with all code filled in for the guided activity and exercises.

### Learning resources

- [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/index.html) - a free, online version of Jake VanderPlas' introduction to data science with Python, includes a chapter on data manipulation with pandas.
- [Python Programming for Data Science](https://www.tomasbeuzen.com/python-programming-for-data-science/README.html) - a website providing a great overview of conducting data science with Python including pandas.

### Finding help with pandas

The [Pandas website](https://pandas.pydata.org/) and [online documentation](http://pandas.pydata.org/pandas-docs/stable/) are useful resources, and of course the indispensible [Stack Overflow has a "pandas" tag](https://stackoverflow.com/questions/tagged/pandas).  There is also a (much younger, much smaller) [sister site dedicated to Data Science questions that has a "pandas" tag](https://datascience.stackexchange.com/questions/tagged/pandas) too.

## Credits

This workshop was created by Walt Gurley and Claire Cahoon, adapted from previous workshop materials by Scott Bailey and Simon Wiles, of Stanford Libraries.